queue: 'Hosted VS2017'


steps:
- checkout: self
  submodules: true


- powershell: 'npm install -g tfx-cli'
  displayName: 'Ensure tfx-cli is installed'
  failOnStderr: false


- task: PowerShell@1
  displayName: 'Create extensions'
  inputs:
    scriptName: src/CreateExtensions.ps1

    workingFolder: src


- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourcesDirectory)/extensions'
  inputs:
    SourceFolder: src

    Contents: '**/*.vsix'

    TargetFolder: '$(Build.SourcesDirectory)/extensions'

    CleanTargetFolder: true

    OverWrite: true

    flattenFolders: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: extensions'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/extensions'

    ArtifactName: extensions


- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourcesDirectory)/scripts'
  inputs:
    SourceFolder: src

    Contents: '*.ps1'

    TargetFolder: '$(Build.SourcesDirectory)/scripts'

    CleanTargetFolder: true

    OverWrite: true

    flattenFolders: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: scripts'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/scripts'

    ArtifactName: scripts

